make v1 connection
Making this a v1 connection until we align our repo with most recent changes in core.

Trying to avoid this error:
AttributeError: 'Namespace' object has no attribute 'v2transport'