Add replacement cycling
Squashed commit of the following:

commit 7553fa6d79e007e59c81f79246b6cc63b350419e
Author: Grant <mpls@posteo.net>
Date:   Wed May 8 17:47:19 2024 -0500

    add replacement cycling

commit 4abc6be7fb1fd4fbdcde32f79fb1d04ed6f0cbc1
Merge: 1b4838c 8589305
Author: Grant <mpls@posteo.net>
Date:   Wed May 8 17:45:16 2024 -0500

    Merge branch 'ez_cycling' into 2024-04-ez-scenario

commit 1b4838c38cb17267f57483f201342dea842dec0a
Merge: d0b334c 579029e
Author: Grant <mpls@posteo.net>
Date:   Wed May 8 17:29:23 2024 -0500

    Merge branch 'rpc-log-test' into 2024-04-ez-scenario

commit 579029e6476af06c7c3518bd054b8b28bedbccde
Author: Grant <mpls@posteo.net>
Date:   Wed May 8 15:05:18 2024 -0500

    add rpc logging

commit 858930527c88048ca821a74b97c777fe3d406329
Author: Grant <mpls@posteo.net>
Date:   Wed May 8 14:45:08 2024 -0500

    add ensure miner to ez testing

commit d88714f24ccdd5f20a5217548dd3bace65c05247
Author: Grant <mpls@posteo.net>
Date:   Wed May 8 14:44:16 2024 -0500

    clarify rpc expression

commit 578431e76bcf305aca88404eb6d8f65979fbe336
Author: Grant <mpls@posteo.net>
Date:   Wed May 8 13:00:29 2024 -0500

    create mini_wallet in tank

commit e3fe12e0c0ed7c81e69e17b6497410e751d634c2
Author: Grant <mpls@posteo.net>
Date:   Wed May 8 12:41:54 2024 -0500

    add logging item in wallet.

commit a0c77dc6c4f5e852923266f7d45006dea1718d0d
Author: Grant <mpls@posteo.net>
Date:   Wed May 8 11:29:36 2024 -0500

    gut test_node to make it work with k8s

commit 548574fe929e44b73ce505d933a6b736592a6cd8
Author: Grant <mpls@posteo.net>
Date:   Wed May 8 11:29:22 2024 -0500

    add start_node logging to test_framework

commit 905baf02a5d34b25be2fb81ea7949013032ed5bc
Author: Grant <mpls@posteo.net>
Date:   Tue May 7 23:56:48 2024 -0500

    look into nodes a lot

commit e4e2a0fb2d81e5483aa67756cea258ab1036725c
Author: Grant <mpls@posteo.net>
Date:   Tue May 7 23:55:55 2024 -0500

    look into nodes a bit

commit 1e25fea928b2a36af053b8d30ca78d1e66104f4f
Author: Grant <mpls@posteo.net>
Date:   Tue May 7 23:47:49 2024 -0500

    Ignore connecting nodes

commit c2eed435a2e4317ff4ee6dcfbacfd457a8c7d9cf
Author: Grant <mpls@posteo.net>
Date:   Tue May 7 23:47:45 2024 -0500

    fix logging

commit beff2d955962c455ac3b34b5f678191a475a1ae3
Author: Grant <mpls@posteo.net>
Date:   Tue May 7 23:43:51 2024 -0500

    add cli help

commit ef94acb6fb7c0e260b6630a857551699a1d64dec
Author: Grant <mpls@posteo.net>
Date:   Tue May 7 23:40:21 2024 -0500

    redo basic cycling instance

commit d0b334cca00beeffd2a36560dba8538b762774a0
Author: Grant <mpls@posteo.net>
Date:   Tue May 7 22:23:00 2024 -0500

    add basic print

commit 58646214f067af384a0029e581437a5502919cfc
Author: Grant <mpls@posteo.net>
Date:   Tue May 7 22:16:27 2024 -0500

    accept bridge's parse_args wholesale

commit 54260d234a40c1a9c10605406340a58a75543207
Author: Grant <mpls@posteo.net>
Date:   Tue May 7 22:09:44 2024 -0500

    add config dance

commit 3f2f78217eebdb4b6f83365a3b4924e6647fc7a2
Author: Grant <mpls@posteo.net>
Date:   Tue May 7 21:58:48 2024 -0500

    specify 1 node; add log info

commit 86f974517a0a8e94b766a28e00bb874c2bc4da02
Author: Grant <mpls@posteo.net>
Date:   Tue May 7 21:56:27 2024 -0500

    add running log to ez testing

commit 1a35297b3479e12465df63360e936c1e900d8104
Author: Grant <mpls@posteo.net>
Date:   Tue May 7 21:47:38 2024 -0500

    tweak ez_testing to try out the test framework

commit b4a4f0679f6a2e0164def36eb36c241e16b41ffe
Author: Grant <mpls@posteo.net>
Date:   Tue May 7 21:33:36 2024 -0500

    add tank to TestNode logic

commit 683f25e26209862681e9ecd2564bf69d07d54281
Author: Grant <mpls@posteo.net>
Date:   Tue May 7 21:21:50 2024 -0500

    bring in warnet, setting k8s as default backend

commit 10076a2efd8da4120038ebfe0c40643e54bcc2bb
Author: Grant <mpls@posteo.net>
Date:   Tue May 7 20:50:29 2024 -0500

    bring in warnet's logging logic

commit 58abccd3d01c9a17ca3cd712716b0e2eb3eb676e
Author: Grant <mpls@posteo.net>
Date:   Tue May 7 20:44:24 2024 -0500

    bring in signal logic from warnet subclass

commit 3fe720024d7300230c982fc7407865310121d8c5
Author: Grant <mpls@posteo.net>
Date:   Tue May 7 20:43:59 2024 -0500

    update the clone's doc string

commit 80c9471cef7dbd54a4519ae6389da0dde3b92966
Author: Grant <mpls@posteo.net>
Date:   Tue May 7 20:42:55 2024 -0500

    make a clone of test node

commit 7cdfd4e21987805b084d0edf24f5095125c144e6
Author: Grant <mpls@posteo.net>
Date:   Sun May 5 22:53:00 2024 -0500

    bypass connect_nodes; update logging

commit 0c0b2276db753502ca06e795c86b4aba6c546570
Author: Grant <mpls@posteo.net>
Date:   Sun May 5 20:07:18 2024 -0500

    make some additional connect_node logging

commit 8f03ea3908e5d85f49c4d3deba90913d0d7f06b5
Author: Grant <mpls@posteo.net>
Date:   Sun May 5 20:07:03 2024 -0500

    make balance logging INFO, not DEBUG

commit 316e58e15ae3e27d062959127d1013b9d28a1003
Author: Grant <mpls@posteo.net>
Date:   Sun May 5 20:06:44 2024 -0500

    bump sleeping to 16

commit 85fb13e2d2b7eb88f259b053133ff52b9fe84cd4
Author: Grant <mpls@posteo.net>
Date:   Sat May 4 19:18:21 2024 -0500

    tweak logging

commit 4d48ac0158e530ef655ea5a12ca9829e0a5b37b0
Author: Grant <mpls@posteo.net>
Date:   Sat May 4 19:17:20 2024 -0500

    switch back to not v2

commit 94ef7dd91cd376fd797a51235ae5498c2a669c2b
Author: Grant <mpls@posteo.net>
Date:   Sat May 4 19:13:22 2024 -0500

    switch to v2

commit bf15d385bb4266f09ce6b0a98c55e8767caa9ea7
Author: Grant <mpls@posteo.net>
Date:   Sat May 4 18:54:48 2024 -0500

    make v1 connection

    Making this a v1 connection until we align our repo with most recent changes in core.

    Trying to avoid this error:
    AttributeError: 'Namespace' object has no attribute 'v2transport'

commit 31a17db7fbd5a26518cab6cc3fabcc7d065dba5a
Author: Grant <mpls@posteo.net>
Date:   Sat May 4 16:28:16 2024 -0500

    add logging trial balloon

commit 2b0c9599992572d3032741ee2d4e2839b3be0f9a
Author: Grant <mpls@posteo.net>
Date:   Sat May 4 16:27:19 2024 -0500

    swap out sleeping for sync_all

commit 400849a293a00888d9671983a9975dfdedb94941
Author: Grant <mpls@posteo.net>
Date:   Sat May 4 13:45:13 2024 -0500

    add warnet framework

commit ccddbfcb61866e7066af766aba42a54c4f58031e
Author: Grant <mpls@posteo.net>
Date:   Sat May 4 13:40:16 2024 -0500

    add cli help

commit f4a7dc53466c6d682ec1401aa3f0807b4259e413
Author: Grant <mpls@posteo.net>
Date:   Tue Apr 30 19:19:34 2024 -0500

    include ariard's replacement cycling code verbatim

commit 0433fdf6285c815f1aebcd1c11f93a92547b8b31
Author: Grant <mpls@posteo.net>
Date:   Tue Apr 30 15:24:15 2024 -0500

    set node minimum

commit 639b1905c3241a6d40b58cc49603688807506e98
Author: dev <mpls@posteo.net>
Date:   Tue Apr 30 14:57:47 2024 -0500

    add simple scenario

remove ez testing

replacement cycling ruff adjustments

remove print statement; add scenario count

reverse parse_args changes

The test_framework_bridge takes care of these parse_args

bubble up changes into subclasses

fixup bridge

reverse test_framework's test_node

enable sync_all via base_class

restore rep cycling to its un-ruffed state

add cli_help